using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Percolator.SourceGenerators;

[Generator]
public sealed class GuidIdGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "Percolator.SourceGenerators.GuidIdAttribute";

    private const string GuidIdAttributeSource = @"// <auto-generated/>
#nullable enable

namespace Percolator.SourceGenerators;

internal enum GuidIdKind
{
    /// <summary>
    /// Cryptographically secure, uncorrelatable random UUID (v4).
    /// Used for security-sensitive tokens, public identities, and entities where time-ordering must not leak.
    /// </summary>
    CryptographicRandom = 0,

    /// <summary>
    /// Monotonically sortable, time-ordered UUID (v7).
    /// Used for append-only logs, messages, and entities indexed in database B-Trees to avoid page fragmentation.
    /// </summary>
    SequentialTimeBased = 1,
}

[global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
internal sealed class GuidIdAttribute : global::System.Attribute
{
    public GuidIdKind Kind { get; }

    public GuidIdAttribute(GuidIdKind kind = GuidIdKind.CryptographicRandom)
    {
        Kind = kind;
    }
}
";

    private static readonly DiagnosticDescriptor TargetMustBeStructDiagnostic = new(
        id: "PERC101",
        title: "[GuidId] can only be applied to structs",
        messageFormat: "[GuidId] can only be applied to struct or record struct declarations",
        category: "Percolator.SourceGenerators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor TargetMustBePartialDiagnostic = new(
        id: "PERC102",
        title: "[GuidId] target must be partial",
        messageFormat: "The type '{0}' must be declared as a partial struct or partial record struct",
        category: "Percolator.SourceGenerators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor TargetMustBeTopLevelNonGenericDiagnostic = new(
        id: "PERC103",
        title: "[GuidId] target must be top-level and non-generic",
        messageFormat: "The type '{0}' must be a top-level, non-generic struct",
        category: "Percolator.SourceGenerators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor TargetUnsupportedAccessibilityDiagnostic = new(
        id: "PERC104",
        title: "[GuidId] target has unsupported accessibility",
        messageFormat: "The type '{0}' must be public or internal to use [GuidId]",
        category: "Percolator.SourceGenerators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "GuidIdAttribute.g.cs",
                SourceText.From(GuidIdAttributeSource, Encoding.UTF8));
        });

        var candidates = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeMetadataName,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => (TypeDeclarationSyntax)ctx.TargetNode)
            .Where(static r => r is not null);

        var compilationAndCandidates = context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(compilationAndCandidates, static (spc, pair) =>
        {
            Execute(spc, pair.Left, pair.Right);
        });
    }

    private static void Execute(SourceProductionContext context, Compilation compilation, ImmutableArray<TypeDeclarationSyntax> records)
    {
        if (records.IsDefaultOrEmpty)
            return;

        foreach (var syntax in records.Distinct())
        {
            var semanticModel = compilation.GetSemanticModel(syntax.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(syntax) is not INamedTypeSymbol typeSymbol)
                continue;

            if (!typeSymbol.IsValueType)
            {
                context.ReportDiagnostic(Diagnostic.Create(TargetMustBeStructDiagnostic, syntax.GetLocation()));
                continue;
            }

            if (typeSymbol.ContainingType is not null || typeSymbol.TypeParameters.Length != 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(TargetMustBeTopLevelNonGenericDiagnostic, syntax.GetLocation(), typeSymbol.Name));
                continue;
            }

            if (!IsPartial(syntax))
            {
                context.ReportDiagnostic(Diagnostic.Create(TargetMustBePartialDiagnostic, syntax.GetLocation(), typeSymbol.Name));
                continue;
            }

            if (typeSymbol.DeclaredAccessibility != Accessibility.Public && typeSymbol.DeclaredAccessibility != Accessibility.Internal)
            {
                context.ReportDiagnostic(Diagnostic.Create(TargetUnsupportedAccessibilityDiagnostic, syntax.GetLocation(), typeSymbol.Name));
                continue;
            }

            int kind = 0; // CryptographicRandom by default
            var attr = typeSymbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == AttributeMetadataName);
            if (attr is not null && attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int k)
            {
                kind = k;
            }

            var source = GuidIdEmitter.GenerateType(typeSymbol, kind);
            var hintName = $"{typeSymbol.Name}.GuidId.g.cs";
            context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static bool IsPartial(TypeDeclarationSyntax syntax)
    {
        foreach (var mod in syntax.Modifiers)
        {
            if (mod.IsKind(SyntaxKind.PartialKeyword))
                return true;
        }
        return false;
    }

    private static class GuidIdEmitter
    {
        public static string GenerateType(INamedTypeSymbol type, int kind)
        {
            var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
            var typeName = type.Name;
            var accessibility = type.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";
            var typeKindKeyword = type.IsRecord ? "record struct" : "struct";

            bool hasValueProperty = type.GetMembers("Value").Any(m => m is IPropertySymbol or IFieldSymbol);
            bool hasGuidConstructor = type.Constructors.Any(c => c.Parameters.Length == 1 && c.Parameters[0].Type.ToDisplayString() == "System.Guid");

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            if (ns is not null)
            {
                sb.Append("namespace ").Append(ns).AppendLine(";");
                sb.AppendLine();
            }

            sb.Append(accessibility).Append(" readonly partial ").Append(typeKindKeyword).Append(" ").Append(typeName);
            sb.Append(" : global::System.IComparable<").Append(typeName).Append(">");
            sb.Append(", global::System.IEquatable<").Append(typeName).Append(">");
            sb.Append(", global::System.ISpanFormattable");
            sb.Append(", global::System.IParsable<").Append(typeName).AppendLine(">");
            sb.AppendLine("{");

            if (!hasValueProperty)
            {
                sb.AppendLine("    public global::System.Guid Value { get; }");
                sb.AppendLine();
            }

            if (!hasGuidConstructor)
            {
                sb.AppendLine($"    public {typeName}(global::System.Guid value)");
                sb.AppendLine("    {");
                sb.AppendLine("        Value = value;");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Indicates whether the identifier has a non-empty, valid GUID value.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public bool IsValid => Value != global::System.Guid.Empty;");
            sb.AppendLine();

            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Domain guard that ensures the identifier is valid and non-empty.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public void EnsureValid(string? paramName = null)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (Value == global::System.Guid.Empty)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (paramName is not null)");
            sb.AppendLine($"                throw new global::System.ArgumentException(\"Identifier '{typeName}' cannot be empty.\", paramName);");
            sb.AppendLine($"            throw new global::System.InvalidOperationException(\"Identifier '{typeName}' cannot be uninitialized or empty.\");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    public static {typeName} FromGuid(global::System.Guid value) => new(value);");
            sb.AppendLine($"    public static {typeName} FromBytes(global::System.ReadOnlySpan<byte> bytes) => new(new global::System.Guid(bytes));");
            sb.AppendLine("    public bool TryWriteBytes(global::System.Span<byte> destination) => Value.TryWriteBytes(destination);");
            sb.AppendLine();

            if (kind == 1) // SequentialTimeBased
            {
                sb.AppendLine($"    public static {typeName} New() => new(global::System.Guid.CreateVersion7());");
                sb.AppendLine($"    public static {typeName} New(global::System.DateTimeOffset timestamp) => new(global::System.Guid.CreateVersion7(timestamp));");
            }
            else // CryptographicRandom
            {
                sb.AppendLine($"    public static {typeName} New() => new(global::System.Guid.NewGuid());");
            }
            sb.AppendLine();

            sb.AppendLine($"    public static explicit operator global::System.Guid({typeName} id) => id.Value;");
            sb.AppendLine($"    public static explicit operator {typeName}(global::System.Guid guid) => new(guid);");
            sb.AppendLine();

            sb.AppendLine($"    public int CompareTo({typeName} other) => Value.CompareTo(other.Value);");
            sb.AppendLine();

            sb.AppendLine("    public override string ToString() => Value.ToString();");
            sb.AppendLine("    public string ToString(string? format, global::System.IFormatProvider? formatProvider) => Value.ToString(format, formatProvider);");
            sb.AppendLine("    public bool TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider) => Value.TryFormat(destination, out charsWritten, format);");
            sb.AppendLine();

            sb.AppendLine($"    public static {typeName} Parse(string s, global::System.IFormatProvider? provider) => new(global::System.Guid.Parse(s, provider));");
            sb.AppendLine($"    public static bool TryParse(string? s, global::System.IFormatProvider? provider, out {typeName} result)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (global::System.Guid.TryParse(s, provider, out var guid))");
            sb.AppendLine("        {");
            sb.AppendLine($"            result = new {typeName}(guid);");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine("        result = default;");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");

            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
