namespace Percolator.Cryptography;

/// <summary>
/// Domain service interface for Signal Group V2 payload encryption/decryption.
///
/// This interface is strictly dedicated to message payload transforms (plaintext <-> ciphertext)
/// and relies only on safe managed types and source-generated ByteArray value objects.
///
/// Key management (generation/derivation/serialization of GroupMasterKey, GroupId, BlobKey)
/// remains the responsibility of <see cref="IGroupCryptographyService" />.
/// </summary>
public interface IGroupV2MessageCryptographyService
{
    /// <summary>
    /// Encrypts a plaintext payload for a group.
    /// </summary>
    /// <param name="groupId">The 32-byte group identifier.</param>
    /// <param name="blobKey">The 32-byte blob key (derived from GroupMasterKey).</param>
    /// <param name="plaintext">Plaintext payload bytes.</param>
    /// <param name="associatedData">Optional associated data (AAD) to bind to the ciphertext.</param>
    /// <returns>Ciphertext bytes.</returns>
    Ciphertext Encrypt(GroupId groupId, BlobKey blobKey, Plaintext plaintext, AssociatedData? associatedData = null);

    /// <summary>
    /// Decrypts a group ciphertext payload back into plaintext.
    /// </summary>
    /// <param name="groupId">The 32-byte group identifier.</param>
    /// <param name="blobKey">The 32-byte blob key (derived from GroupMasterKey).</param>
    /// <param name="ciphertext">Ciphertext payload bytes.</param>
    /// <param name="associatedData">Optional associated data (AAD) expected to be bound to the ciphertext.</param>
    /// <returns>Plaintext payload bytes.</returns>
    /// <exception cref="CryptographicException">Thrown when authentication fails or the ciphertext is invalid.</exception>
    Plaintext Decrypt(GroupId groupId, BlobKey blobKey, Ciphertext ciphertext, AssociatedData? associatedData = null);
}
