<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Percolator.Cryptography</AssemblyName>
        <RootNamespace>Percolator.Cryptography</RootNamespace>
    </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Percolator.CryptographyTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.31.1" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Cng" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\manifest.proto" GrpcServices="None" />
  </ItemGroup>

</Project>
