<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Percolator.Cryptography</AssemblyName>
        <RootNamespace>Percolator.Cryptography</RootNamespace>
    </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Percolator.CryptographyTests" />
    <ProjectReference Include="..\Percolator.Contracts\Percolator.Contracts.csproj" />
  </ItemGroup>

</Project>
