<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Percolator.Cryptography</AssemblyName>
        <RootNamespace>Percolator.Cryptography</RootNamespace>
    </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Percolator.CryptographyTests" />
    <ProjectReference Include="..\Percolator.Contracts\Percolator.Contracts.csproj" />
    <ProjectReference Include="..\Percolator.SourceGenerators\Percolator.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="9.0.6" />
  </ItemGroup>

</Project>
