<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.27.2" />
    <PackageReference Include="Grpc.Core.Api" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\messaging.proto" GrpcServices="Both" ProtoRoot="Protos" />
    <Protobuf Include="Protos\internal_messaging.proto" GrpcServices="None" ProtoRoot="Protos" />
    <Protobuf Include="Protos\discovery.proto" GrpcServices="None" ProtoRoot="Protos" />
    <Protobuf Include="Protos\file_transfer.proto" GrpcServices="Both" ProtoRoot="Protos" />
  </ItemGroup>

</Project>
