// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Percolator.Infrastructure.Persistence;

#nullable disable

namespace Percolator.Infrastructure.Percolator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PercolatorDbContext))]
    [Migration("20251201045224_AddSessions")]
    partial class AddSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Percolator.Dht.DhtNode", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DhtNodes");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Cryptography.PendingSessionDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Invitation")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RemotePeerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "RemotePeerId");

                    b.ToTable("PendingSessions", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Identity.PeerIdentityDbo", b =>
                {
                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PeerIdentities", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Identity.PeerIdentityKeyDbo_V2", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("NotBeforeUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicKeySpki")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("PeerId");

                    b.ToTable("PeerIdentityKeys_V2", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Identity.PeerVerificationDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("NotBeforeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("VerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint");

                    b.HasIndex("PeerId", "Fingerprint");

                    b.ToTable("PeerVerifications", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupConversationGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "GroupConversationGuid")
                        .IsUnique();

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationParticipantDbo", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConversationId", "ParticipantId");

                    b.ToTable("ConversationParticipants", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DeliveredReceiptDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId1")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId1");

                    b.HasIndex("ConversationId", "MessageGuid", "RecipientId")
                        .IsUnique();

                    b.ToTable("DeliveredReceipts", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DirectSessionConversationDbo", b =>
                {
                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DirectSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.HasKey("SelfIdentityId", "DirectSessionId");

                    b.HasIndex("SelfIdentityId", "ConversationId")
                        .IsUnique();

                    b.ToTable("DirectSessionConversations", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DirectSessionDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RemotePeerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "RemotePeerId");

                    b.HasIndex("SelfIdentityId", "SessionId");

                    b.ToTable("DirectSession", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DiscoveredPeerDbo", b =>
                {
                    b.Property<string>("DiscoveryKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BoundPeerId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicKeyHash")
                        .HasColumnType("BLOB");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscoveryKey");

                    b.HasIndex("PublicKeyHash");

                    b.ToTable("DiscoveredPeers", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DiscoveredPeerEndpointDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscoveryKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryKey", "Host", "Port")
                        .IsUnique();

                    b.ToTable("DiscoveredPeerEndpoints", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DoubleRatchetSessionDbo", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DhRatchetPrivateKey")
                        .HasColumnType("BLOB");

                    b.Property<ulong>("PreviousChainLength")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RatchetFlag")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ReceivingChainKey")
                        .HasColumnType("BLOB");

                    b.Property<ulong>("ReceivingCounter")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RootKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SendingChainKey")
                        .HasColumnType("BLOB");

                    b.Property<ulong>("SendingCounter")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TheirDhRatchetPublicKey")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("TheirIdentityPublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("SelfIdentityId", "UpdatedAt");

                    b.ToTable("DoubleRatchetSessions", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.EmojiReactionDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReactorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId1");

                    b.HasIndex("ConversationId", "MessageGuid", "ReactorId", "Emoji")
                        .IsUnique();

                    b.ToTable("EmojiReactions", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GroupAdminKeyDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AdminPublicKeySpki")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "AddedAtUtc");

                    b.HasIndex("ConversationId", "RevokedAtUtc");

                    b.ToTable("GroupAdminKeys", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GroupAdminOpDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActingAdminPeerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OpId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "OpId")
                        .IsUnique();

                    b.ToTable("GroupAdminOps", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GroupAdminStateDbo", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("LastCommittedKeyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("NextAdminSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConversationId");

                    b.ToTable("GroupAdminStates", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GroupManagerStateDbo", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ConversationId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("GroupManagerStates", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GroupMemberDbo", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("MemberSpkiHash")
                        .HasColumnType("BLOB");

                    b.Property<long>("JoinedAtSequence")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("MemberSpki")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConversationId", "MemberSpkiHash");

                    b.HasIndex("ConversationId");

                    b.ToTable("GroupMembers", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GrpcEndPointRoutingDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeerId", "Host", "Port")
                        .IsUnique();

                    b.ToTable("PeerRoutingGrpcEndPoints", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.KeyAdoptionConfirmationDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AdopterIdentityKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("KeyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Signature")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "KeyVersion", "SentAtUtc");

                    b.ToTable("KeyAdoptionConfirmations", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.MessageDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "MessageGuid")
                        .IsUnique();

                    b.HasIndex("ConversationId", "SentAt");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.MessageQueueItemDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AckId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Blob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("EnqueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipientPeerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AckId")
                        .IsUnique();

                    b.HasIndex("EnqueuedAtUtc");

                    b.HasIndex("RecipientPeerId");

                    b.HasIndex("RecipientPeerId", "EnqueuedAtUtc");

                    b.ToTable("MessageQueue", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.OneTimePreKeyDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeerIdentityKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerIdentityKeyId");

                    b.ToTable("OneTimePreKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.ToTable("PeerIdentityKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerPublicSigningKeyDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ActiveAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PublicKeyHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.HasIndex("PublicKeyHash")
                        .IsUnique();

                    b.HasIndex("PeerId", "ActiveAtUtc");

                    b.HasIndex("PeerId", "ExpiredAtUtc");

                    b.ToTable("PeerPublicSigningKeys", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerRoutingProfileDbo", b =>
                {
                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DirectMessagePublicKey")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("ReachabilityLastChangeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReachabilityStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeerId");

                    b.ToTable("PeerRoutingProfiles", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PreHandshakeSessionDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("InitialRootKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("LocalRequestId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RecipientPublicKeyHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RemoteIdentityKeySpki")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RemoteIdentityKeySpkiHash")
                        .HasColumnType("BLOB");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId");

                    b.HasIndex("SelfIdentityId", "ExpiresAtUtc");

                    b.HasIndex("SelfIdentityId", "LocalRequestId")
                        .IsUnique();

                    b.HasIndex("SelfIdentityId", "RecipientPublicKeyHash");

                    b.HasIndex("SelfIdentityId", "RemoteIdentityKeySpkiHash", "CreatedAtUtc");

                    b.ToTable("PreHandshakeSessions", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.RatchetKeyIndexDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DirectSessionId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RatchetPublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectSessionId", "SelfIdentityId");

                    b.HasIndex("SelfIdentityId", "RatchetPublicKey")
                        .IsUnique();

                    b.ToTable("RatchetKeyIndex", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ReadReceiptDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReaderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId1");

                    b.HasIndex("ConversationId", "MessageGuid", "ReaderId")
                        .IsUnique();

                    b.ToTable("ReadReceipts", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.RelayLinkDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelayPeerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeerId", "RelayPeerId")
                        .IsUnique();

                    b.ToTable("PeerRoutingRelays", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUsedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastUsedUtc");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PeerId");

                    b.ToTable("SelfIdentity", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityKeysDbo", b =>
                {
                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("IdentitySigningKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SignedPreKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("SelfIdentityId");

                    b.ToTable("SelfIdentityKeys", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityKnownPeerDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "PeerId")
                        .IsUnique();

                    b.ToTable("SelfIdentityKnownPeer", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfOneTimePreKeyDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OneTimePreKeyId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("OneTimePreKeyPrivate")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("OneTimePreKeyPublicSpki")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "OneTimePreKeyId")
                        .IsUnique();

                    b.ToTable("SelfOneTimePreKeys", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfPreKeySignedDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PreKeySignature")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SignedPreKeyId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SignedPreKeyPrivate")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SignedPreKeyPublicSpki")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "SignedPreKeyId")
                        .IsUnique();

                    b.ToTable("SelfPreKeySigned", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SenderKeyDbo", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderPeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ChainKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SigningKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ConversationId", "SenderPeerId");

                    b.HasIndex("ConversationId");

                    b.ToTable("SenderKeys", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SessionDbo", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AssociatedData")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DhRatchetPrivateKey")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("LastUsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PrevChainLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RecvChainKey")
                        .HasColumnType("BLOB");

                    b.Property<ulong>("RecvCounter")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RemotePeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RemoteRatchetKey")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RootKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SendChainKey")
                        .HasColumnType("BLOB");

                    b.Property<ulong>("SendCounter")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "SelfIdentityId");

                    b.HasIndex("SelfIdentityId", "RemotePeerId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SignedPreKeyDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeerIdentityKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Signature")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerIdentityKeyId");

                    b.ToTable("SignedPreKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SkippedMessageKeyDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("MessageKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ulong>("MessageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RatchetKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "SelfIdentityId");

                    b.HasIndex("SelfIdentityId", "SessionId", "RatchetKey", "MessageNumber")
                        .IsUnique();

                    b.ToTable("SkippedMessageKeys", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.TlsCertificateRoutingDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RawDataHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.HasIndex("RawDataHash");

                    b.ToTable("PeerRoutingTlsCertificates", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Identity.PeerIdentityKeyDbo_V2", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Identity.PeerIdentityDbo", "Peer")
                        .WithMany("Keys")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Identity.PeerVerificationDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Identity.PeerIdentityDbo", null)
                        .WithMany("Verifications")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationParticipantDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DeliveredReceiptDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DirectSessionDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DiscoveredPeerEndpointDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.DiscoveredPeerDbo", null)
                        .WithMany()
                        .HasForeignKey("DiscoveryKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DoubleRatchetSessionDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.EmojiReactionDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GroupMemberDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.GroupManagerStateDbo", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GrpcEndPointRoutingDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerRoutingProfileDbo", null)
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.MessageDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.OneTimePreKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", "PeerIdentityKey")
                        .WithMany("OneTimePreKeys")
                        .HasForeignKey("PeerIdentityKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeerIdentityKey");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Identity.PeerIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.RatchetKeyIndexDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.DoubleRatchetSessionDbo", "Session")
                        .WithMany()
                        .HasForeignKey("DirectSessionId", "SelfIdentityId")
                        .HasPrincipalKey("SessionId", "SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ReadReceiptDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.RelayLinkDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerRoutingProfileDbo", null)
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityKeysDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithOne("Keys")
                        .HasForeignKey("Percolator.Infrastructure.Persistence.SelfIdentityKeysDbo", "SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityKnownPeerDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfOneTimePreKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfPreKeySignedDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SenderKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.GroupManagerStateDbo", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SessionDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SignedPreKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", "PeerIdentityKey")
                        .WithMany("SignedPreKeys")
                        .HasForeignKey("PeerIdentityKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeerIdentityKey");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SkippedMessageKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.DoubleRatchetSessionDbo", "Session")
                        .WithMany("SkippedMessageKeys")
                        .HasForeignKey("SessionId", "SelfIdentityId")
                        .HasPrincipalKey("SessionId", "SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.TlsCertificateRoutingDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerRoutingProfileDbo", null)
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Identity.PeerIdentityDbo", b =>
                {
                    b.Navigation("Keys");

                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationDbo", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DoubleRatchetSessionDbo", b =>
                {
                    b.Navigation("SkippedMessageKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", b =>
                {
                    b.Navigation("OneTimePreKeys");

                    b.Navigation("SignedPreKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityDbo", b =>
                {
                    b.Navigation("Keys");
                });
#pragma warning restore 612, 618
        }
    }
}
