// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Percolator.Infrastructure.Persistence;

#nullable disable

namespace Percolator.Infrastructure.Migrations
{
    [DbContext(typeof(PercolatorDbContext))]
    [Migration("20250824175529_AddPeerConnection")]
    partial class AddPeerConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Percolator.Dht.DhtNode", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DhtNodes");
                });

            modelBuilder.Entity("Percolator.Identity.Peer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Peers");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GrpcEndPointDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.ToTable("GrpcEndPoints");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.OneTimePreKeyDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeerIdentityKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerIdentityKeyId");

                    b.ToTable("OneTimePreKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerConnectionDbo", b =>
                {
                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DirectMessagePublicKey")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("TEXT");

                    b.HasKey("PeerId");

                    b.HasIndex("DirectMessagePublicKey");

                    b.ToTable("PeerConnections");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.ToTable("PeerIdentityKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SignedPreKeyDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeerIdentityKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Signature")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerIdentityKeyId");

                    b.ToTable("SignedPreKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.TlsCertificateDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RawDataHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.HasIndex("RawDataHash");

                    b.ToTable("TlsCertificates");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GrpcEndPointDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerConnectionDbo", "PeerConnection")
                        .WithMany("GrpcEndPoints")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeerConnection");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.OneTimePreKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", "PeerIdentityKey")
                        .WithMany("OneTimePreKeys")
                        .HasForeignKey("PeerIdentityKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeerIdentityKey");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerConnectionDbo", b =>
                {
                    b.HasOne("Percolator.Identity.Peer", null)
                        .WithOne()
                        .HasForeignKey("Percolator.Infrastructure.Persistence.PeerConnectionDbo", "PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", b =>
                {
                    b.HasOne("Percolator.Identity.Peer", "Peer")
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SignedPreKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", "PeerIdentityKey")
                        .WithMany("SignedPreKeys")
                        .HasForeignKey("PeerIdentityKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeerIdentityKey");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.TlsCertificateDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerConnectionDbo", "PeerConnection")
                        .WithMany("TlsCertificates")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeerConnection");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerConnectionDbo", b =>
                {
                    b.Navigation("GrpcEndPoints");

                    b.Navigation("TlsCertificates");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", b =>
                {
                    b.Navigation("OneTimePreKeys");

                    b.Navigation("SignedPreKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
