// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Percolator.Infrastructure.Persistence;

#nullable disable

namespace Percolator.Infrastructure.Migrations
{
    [DbContext(typeof(PercolatorDbContext))]
    [Migration("20250831223336_AddSelfIdentityPartitionToDoubleRatchet")]
    partial class AddSelfIdentityPartitionToDoubleRatchet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Percolator.Dht.DhtNode", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DhtNodes");
                });

            modelBuilder.Entity("Percolator.Identity.Peer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Peers");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ChannelId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "ChannelId");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationParticipantDbo", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConversationId", "ParticipantId");

                    b.ToTable("ConversationParticipants", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DirectSessionDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RemotePeerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RemotePeerId");

                    b.HasIndex("SelfIdentityId", "RemotePeerId");

                    b.HasIndex("SelfIdentityId", "SessionId");

                    b.ToTable("DirectSession", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DoubleRatchetSessionDbo", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DhRatchetPrivateKey")
                        .HasColumnType("BLOB");

                    b.Property<ulong>("PreviousChainLength")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RatchetFlag")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ReceivingChainKey")
                        .HasColumnType("BLOB");

                    b.Property<ulong>("ReceivingCounter")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RootKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SendingChainKey")
                        .HasColumnType("BLOB");

                    b.Property<ulong>("SendingCounter")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TheirDhRatchetPublicKey")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("TheirIdentityPublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("DoubleRatchetSessions", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GrpcEndPointDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.ToTable("GrpcEndPoints");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.MessageDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "SentAt");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.OneTimePreKeyDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeerIdentityKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerIdentityKeyId");

                    b.ToTable("OneTimePreKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerConnectionDbo", b =>
                {
                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DirectMessagePublicKey")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("TEXT");

                    b.HasKey("PeerId");

                    b.HasIndex("DirectMessagePublicKey");

                    b.ToTable("PeerConnections");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.ToTable("PeerIdentityKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PeerId");

                    b.ToTable("SelfIdentity", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityKnownPeerDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "PeerId")
                        .IsUnique();

                    b.ToTable("SelfIdentityKnownPeer", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SignedPreKeyDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeerIdentityKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Signature")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerIdentityKeyId");

                    b.ToTable("SignedPreKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SkippedMessageKeyDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("MessageKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ulong>("MessageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RatchetKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "RatchetKey", "MessageNumber")
                        .IsUnique();

                    b.ToTable("SkippedMessageKeys", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.TlsCertificateDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RawDataHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.HasIndex("RawDataHash");

                    b.ToTable("TlsCertificates");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationParticipantDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DirectSessionDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerConnectionDbo", null)
                        .WithMany()
                        .HasForeignKey("RemotePeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GrpcEndPointDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerConnectionDbo", "PeerConnection")
                        .WithMany("GrpcEndPoints")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeerConnection");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.MessageDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.OneTimePreKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", "PeerIdentityKey")
                        .WithMany("OneTimePreKeys")
                        .HasForeignKey("PeerIdentityKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeerIdentityKey");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerConnectionDbo", b =>
                {
                    b.HasOne("Percolator.Identity.Peer", null)
                        .WithOne()
                        .HasForeignKey("Percolator.Infrastructure.Persistence.PeerConnectionDbo", "PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", b =>
                {
                    b.HasOne("Percolator.Identity.Peer", "Peer")
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityKnownPeerDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SignedPreKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", "PeerIdentityKey")
                        .WithMany("SignedPreKeys")
                        .HasForeignKey("PeerIdentityKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeerIdentityKey");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SkippedMessageKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.DoubleRatchetSessionDbo", "Session")
                        .WithMany("SkippedMessageKeys")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.TlsCertificateDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerConnectionDbo", "PeerConnection")
                        .WithMany("TlsCertificates")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeerConnection");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationDbo", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DoubleRatchetSessionDbo", b =>
                {
                    b.Navigation("SkippedMessageKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerConnectionDbo", b =>
                {
                    b.Navigation("GrpcEndPoints");

                    b.Navigation("TlsCertificates");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerIdentityKeyDbo", b =>
                {
                    b.Navigation("OneTimePreKeys");

                    b.Navigation("SignedPreKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
