// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Percolator.Infrastructure.Persistence;

#nullable disable

namespace Percolator.Infrastructure.Migrations
{
    [DbContext(typeof(PercolatorDbContext))]
    [Migration("20250819235526_AddPreKeyBundleTable")]
    partial class AddPreKeyBundleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Percolator.Identity.Peer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Peers");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PreKeyBundleDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpirationDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("IdentityAgreementKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("IdentitySigningKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("OneTimePreKey")
                        .HasColumnType("BLOB");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SignedPreKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SignedPreKeySignature")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.ToTable("PreKeyBundles");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PreKeyBundleDbo", b =>
                {
                    b.HasOne("Percolator.Identity.Peer", "Peer")
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });
#pragma warning restore 612, 618
        }
    }
}
