// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Percolator.Infrastructure.Persistence;

#nullable disable

namespace Percolator.Infrastructure.Migrations
{
    [DbContext(typeof(PercolatorDbContext))]
    partial class PercolatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Percolator.Dht.DhtNode", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DhtNodes");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Chat.Persistence.DeliveryCertificateDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<uint>("RelayPeerId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SelfId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Signature")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("SelfId", "RelayPeerId")
                        .IsUnique();

                    b.ToTable("DeliveryCertificates", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Chat.Persistence.GroupMemberDbo", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicIdentityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("PeerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RemovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("SelfId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConversationId", "PublicIdentityId");

                    b.HasIndex("ConversationId");

                    b.ToTable("GroupMembers", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Chat.Persistence.GroupStateDbo", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Epoch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicParams")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<uint>("RelayPeerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ConversationId");

                    b.ToTable("GroupStates", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Chat.Persistence.PendingGroupInvitationDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CreatorIdentityKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialMembersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("InviterPeerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("PendingGroupInvitations", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Chat.Persistence.SenderKeyRecordDbo", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("SenderPeerId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RecordBytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ConversationId", "SenderPeerId", "DeviceId");

                    b.ToTable("SenderKeyRecords", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Cryptography.PendingSessionDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CallbackEndpointHost")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CallbackEndpointPort")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Invitation")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("InviterIdentityKey")
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsRelayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("RelayHostPeerId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RemotePeerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestCorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "RemotePeerId");

                    b.ToTable("PendingSessions", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Cryptography.SentInvitationDbo", b =>
                {
                    b.Property<uint>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestCorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("InviteRelayHostPeerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InviteRouteKind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OneTimePreKeyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SignedPreKeyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetEndpointHost")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetEndpointPort")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("TargetPeerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SelfIdentityId", "RequestCorrelationId");

                    b.HasIndex("SelfIdentityId", "ExpiresAtUtc");

                    b.ToTable("SentInvitations", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Identity.PeerIdentityDbo", b =>
                {
                    b.Property<uint>("PeerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastKnownProfileRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("PrimaryDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProfileKey")
                        .HasColumnType("BLOB");

                    b.Property<Guid>("PublicIdentityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublicIdentityId")
                        .IsUnique();

                    b.ToTable("PeerIdentities", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Identity.PeerIdentityKeyDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("NotBeforeUtc")
                        .HasColumnType("TEXT");

                    b.Property<uint>("PeerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKeySpki")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("PeerId");

                    b.ToTable("PeerIdentityKeys", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Identity.PeerVerificationDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("NotBeforeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<uint>("PeerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("VerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint");

                    b.HasIndex("PeerId", "Fingerprint");

                    b.ToTable("PeerVerifications", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<uint>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("SelfIdentityId");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationParticipantDbo", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConversationId", "ParticipantId");

                    b.ToTable("ConversationParticipants", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DirectSessionConversationDbo", b =>
                {
                    b.Property<uint>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DirectSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.HasKey("SelfIdentityId", "DirectSessionId");

                    b.HasIndex("SelfIdentityId", "ConversationId")
                        .IsUnique();

                    b.ToTable("DirectSessionConversations", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DirectSessionDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RemotePeerId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "RemotePeerId");

                    b.HasIndex("SelfIdentityId", "SessionId");

                    b.ToTable("DirectSession", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DiscoveredPeerDbo", b =>
                {
                    b.Property<string>("DiscoveryKey")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("BoundPeerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicKeyHash")
                        .HasColumnType("BLOB");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscoveryKey");

                    b.HasIndex("PublicKeyHash");

                    b.ToTable("DiscoveredPeers", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DiscoveredPeerEndpointDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscoveryKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryKey", "Host", "Port")
                        .IsUnique();

                    b.ToTable("DiscoveredPeerEndpoints", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GroupCryptoStateDbo", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("GroupMasterKeyBytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ConversationId");

                    b.ToTable("GroupCryptoStates", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GrpcEndPointRoutingDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<uint>("PeerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeerId", "Host", "Port")
                        .IsUnique();

                    b.ToTable("PeerRoutingGrpcEndPoints", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.MessageDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicMessageId")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("SenderPeerId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SenderSelfId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "PublicMessageId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "SentAt");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.MessageQueueItemDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AckId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Blob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("EnqueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RecipientPkh")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("AckId")
                        .IsUnique();

                    b.HasIndex("EnqueuedAtUtc");

                    b.HasIndex("RecipientPkh");

                    b.HasIndex("RecipientPkh", "EnqueuedAtUtc");

                    b.ToTable("MessageQueue", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.OneTimePreKeyDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("PreKeyBundleId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PreKeyBundleId");

                    b.ToTable("OneTimePreKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerPublicSigningKeyDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ActiveAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<uint>("PeerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PublicKeyHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.HasIndex("PublicKeyHash")
                        .IsUnique();

                    b.HasIndex("PeerId", "ActiveAtUtc");

                    b.HasIndex("PeerId", "ExpiredAtUtc");

                    b.ToTable("PeerPublicSigningKeys", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerRouteCandidateDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndpointHost")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndpointPort")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("RelayHostPeerId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RemotePeerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RouteKind")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "RemotePeerId", "RouteKind", "EndpointHost", "EndpointPort", "RelayHostPeerId")
                        .IsUnique();

                    b.ToTable("PeerRouteCandidates", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PeerRoutingProfileDbo", b =>
                {
                    b.Property<uint>("PeerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("DirectMessagePublicKey")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("ReachabilityLastChangeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReachabilityStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeerId");

                    b.ToTable("PeerRoutingProfiles", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PreHandshakeSessionDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("InitialRootKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("LocalRequestId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RecipientPublicKeyHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RemoteIdentityKeySpki")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RemoteIdentityKeySpkiHash")
                        .HasColumnType("BLOB");

                    b.Property<uint>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId");

                    b.HasIndex("SelfIdentityId", "ExpiresAtUtc");

                    b.HasIndex("SelfIdentityId", "LocalRequestId")
                        .IsUnique();

                    b.HasIndex("SelfIdentityId", "RecipientPublicKeyHash");

                    b.HasIndex("SelfIdentityId", "RemoteIdentityKeySpkiHash", "CreatedAtUtc");

                    b.ToTable("PreHandshakeSessions", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PreKeyBundleDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PeerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.ToTable("PreKeyBundles");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.RatchetKeyIndexDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DirectSessionId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RatchetPublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<uint>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "RatchetPublicKey")
                        .IsUnique();

                    b.ToTable("RatchetKeyIndex", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ReadReceiptDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageGuid")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReaderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "MessageGuid", "ReaderId")
                        .IsUnique();

                    b.ToTable("ReadReceipts", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.RelayBlindedRosterDbo", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberPublicIdentityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ConversationId", "MemberPublicIdentityId");

                    b.ToTable("RelayBlindedRosters", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.RelayGroupStateDbo", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Epoch")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("GroupPublicParams")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConversationId");

                    b.ToTable("RelayGroupStates", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.RelayLinkDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<uint>("PeerId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RelayPeerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeerId", "RelayPeerId")
                        .IsUnique();

                    b.ToTable("PeerRoutingRelays", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.RelayOutboxDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<uint>("DestinationPeerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("RelayOutbox", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityDbo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ActiveIdentityKeyFingerprint")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ActiveIdentityKeySpki")
                        .HasColumnType("BLOB");

                    b.Property<uint>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("EncryptedProfileData")
                        .HasColumnType("BLOB");

                    b.Property<long>("LastUsedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListeningPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProfileKey")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ProfileNonce")
                        .HasColumnType("BLOB");

                    b.Property<int>("ProfileRevision")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProfileTag")
                        .HasColumnType("BLOB");

                    b.Property<Guid>("PublicIdentityId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RelayDeliveryRootKey")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ZkServerSecretParamsSeed")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ActiveIdentityKeyFingerprint");

                    b.HasIndex("LastUsedUtc");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublicIdentityId");

                    b.ToTable("SelfIdentity", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityKeysDbo", b =>
                {
                    b.Property<uint>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("IdentitySigningKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SignedPreKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("SelfIdentityId");

                    b.ToTable("SelfIdentityKeys", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityKnownPeerDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PeerId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "PeerId")
                        .IsUnique();

                    b.ToTable("SelfIdentityKnownPeer", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfOneTimePreKeyDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OneTimePreKeyId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("OneTimePreKeyPrivate")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("OneTimePreKeyPublicSpki")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid?>("ReservedForRequestCorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReservedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<uint>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "OneTimePreKeyId")
                        .IsUnique();

                    b.HasIndex("SelfIdentityId", "ReservedForRequestCorrelationId")
                        .IsUnique()
                        .HasFilter("\"ReservedForRequestCorrelationId\" IS NOT NULL");

                    b.ToTable("SelfOneTimePreKeys", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfPreKeySignedDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PreKeySignature")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<uint>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SignedPreKeyId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SignedPreKeyPrivate")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SignedPreKeyPublicSpki")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("SelfIdentityId", "SignedPreKeyId")
                        .IsUnique();

                    b.ToTable("SelfPreKeySigned", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SessionDbo", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("SelfIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AssociatedData")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DhRatchetPrivateKey")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("LastUsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PrevChainLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RecvChainKey")
                        .HasColumnType("BLOB");

                    b.Property<ulong>("RecvCounter")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RemotePeerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RemoteRatchetKey")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RootKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SendChainKey")
                        .HasColumnType("BLOB");

                    b.Property<ulong>("SendCounter")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "SelfIdentityId");

                    b.HasIndex("SelfIdentityId", "RemotePeerId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SignedPreKeyDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("PreKeyBundleId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Signature")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PreKeyBundleId");

                    b.ToTable("SignedPreKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Chat.Persistence.GroupMemberDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Chat.Persistence.GroupStateDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Cryptography.SentInvitationDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Identity.PeerIdentityKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Identity.PeerIdentityDbo", "Peer")
                        .WithMany("Keys")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Identity.PeerVerificationDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Identity.PeerIdentityDbo", null)
                        .WithMany("Verifications")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationParticipantDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DirectSessionDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.DiscoveredPeerEndpointDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.DiscoveredPeerDbo", null)
                        .WithMany()
                        .HasForeignKey("DiscoveryKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GroupCryptoStateDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.GrpcEndPointRoutingDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerRoutingProfileDbo", null)
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.MessageDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.OneTimePreKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PreKeyBundleDbo", "PreKeyBundle")
                        .WithMany("OneTimePreKeys")
                        .HasForeignKey("PreKeyBundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreKeyBundle");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PreKeyBundleDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Identity.PeerIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ReadReceiptDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.ConversationDbo", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.RelayLinkDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PeerRoutingProfileDbo", null)
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityKeysDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithOne("Keys")
                        .HasForeignKey("Percolator.Infrastructure.Persistence.SelfIdentityKeysDbo", "SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityKnownPeerDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfOneTimePreKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfPreKeySignedDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SessionDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.SelfIdentityDbo", null)
                        .WithMany()
                        .HasForeignKey("SelfIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SignedPreKeyDbo", b =>
                {
                    b.HasOne("Percolator.Infrastructure.Persistence.PreKeyBundleDbo", "PreKeyBundle")
                        .WithMany("SignedPreKeys")
                        .HasForeignKey("PreKeyBundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreKeyBundle");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Identity.PeerIdentityDbo", b =>
                {
                    b.Navigation("Keys");

                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.ConversationDbo", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.PreKeyBundleDbo", b =>
                {
                    b.Navigation("OneTimePreKeys");

                    b.Navigation("SignedPreKeys");
                });

            modelBuilder.Entity("Percolator.Infrastructure.Persistence.SelfIdentityDbo", b =>
                {
                    b.Navigation("Keys");
                });
#pragma warning restore 612, 618
        }
    }
}
